### ISSUE TITLE
Any other place then baidu?

### ISSUE THREAD

**Issue by ahmadmughees** [lijfrank-open/SFCHD-SCALE#1]
Hi, 
Thanks a lot for your great work and for uploading the dataset. 
Can you please host this data anywhere besides Baidu for international users as well? 

Thanks.

**Comment by lijfrank-open** [comment]
> Hi, Thanks a lot for your great work and for uploading the dataset. Can you please host this data anywhere besides Baidu for international users as well?
> 
> Thanks.

Uploading to Google Drive. However, the upload speed is plodding, please wait a moment.
